### ISSUE TITLE
Error building 'double-quoted include ...'

### ISSUE THREAD

**Issue by louiechristie** [zappar-xr/zapbox-xrit-demo#3]
## Steps to reproduce:

-  Try to build the project in XCode

## Screenshots

![image](https://github.com/zappar-xr/zapbox-xrit-demo/assets/6807448/ab27c6af-36b8-4370-89f1-b20d9417925d)

Source - https://discord.com/channels/1047498510506917968/1047499955838922912/1147277425089191987

## What I've tried

- Googling the error:

  - Looks like its an issue brought in by XCode 14.3 with Unity: https://forum.unity.com/threads/xcode-14-3-breaks-my-previously-working-ios-build-with-double-quote-errors.1420130/
  - **Workaround may be to downgrade XCode or upgrade cocoapods?**

**Comment by tangobravo** [comment]
Thanks for reporting.

Looks like this issue is the result of accepting Xcode's "Update to recommend settings" project warning, which enables the Module Verifier build setting for the UnityFramework target.

The fix is to do a clean export of the build from Unity and make sure not to accept the suggestion from Xcode to change the settings. Alternatively, ensure the "Enable Module Verifier" build setting is set to "No" in for the UnityFramework target.

Closing without making any change as this is unrelated to the Zapbox plugin.
